# Generated by Django 6.1 on 2026-08-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_task_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
