# Generated by Django 6.1 on 2026-08-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('student', 'Student')], max_length=20, unique=True),
        ),
    ]
