# Generated by Django 6.1 on 2026-08-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_type',
            field=models.CharField(choices=[('summarize', 'Summarize'), ('explain', 'Explain')], max_length=20),
        ),
    ]
